Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: organizations/ordererOrganizations/net/orderers/orderer.net/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererOrg.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererOrg.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererOrg.admin')"
    OrdererEndpoints:
      - orderer.net:7050

  - &Org1
    Name: Org1MSP
    ID: Org1MSP
    MSPDir: organizations/peerOrganizations/org1.net/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin')"
    AnchorPeers:
      - Host: peer0.org1.net
        Port: 7051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('Org1MSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('Org1MSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('Org1MSP.admin')"
    LifecycleEndorsement:
      Type: Signature
      Rule: "OR('Org1MSP.member')"
    Endorsement:
      Type: Signature
      Rule: "OR('Org1MSP.member')"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  Addresses:
    - orderer.net:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('OrdererMSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('OrdererMSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('OrdererMSP.admin')"
    BlockValidation:
      Type: Signature
      Rule: "OR('OrdererMSP.member')"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('Org1MSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('Org1MSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('Org1MSP.admin')"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  ChannelProfile:
    <<: *ChannelDefaults
    Consortium: SampleConsortium
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
      Capabilities: *ApplicationCapabilities

  GenesisProfile:
    <<: *ChannelDefaults
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org1
    Orderer:
      <<: *OrdererDefaults
      OrdererType: solo
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
